### PR TITLE
Add Synaptic Plasticity use case

### PR DESCRIPTION
**Pull request by clupascu**
Synaptic plasticity usecase added

### CODE REVIEW

**Comment by antonelepfl** [comment]
Good thank you Carmen,
I have a couple of things about this.
1) As you see in this PR there is an [error](https://travis-ci.org/antonelepfl/usecases/builds/639851452?utm_source=github_status&utm_medium=notification) related to some `,` that you added (and this leads to malformed JSON. Could you please remove the last comma on [usecases?](https://github.com/antonelepfl/usecases/pull/294/files#diff-792ef00d694f11cf071142152aecd528R865_)
2) I see that the notebook is using Python 2. I'm wondering why this is like that and not Python 3?
3) I tried to run the simulation on Piz-Daint and I get some errors. You can check the logs at `/users/bp000037/unicore_jobs/828c9133-4ebd-4476-95bc-9f22f2532465`
4) I would need an image that is representative for this use case

**Comment by clupascu** [comment]
I removed the last comma. The notebook is Python3. The link is this one https://collab.humanbrainproject.eu/#/collab/72837/nav/493746
It has no hpc so which simulation did you run? 
Can we put the usecase online without an image for now? I will provide one asap.

**Comment by antonelepfl** [comment]
I just tried to clone the notebook and run it but I guess you added a wrong **file** in the [usecases.json](https://github.com/antonelepfl/usecases/pull/294/files#diff-792ef00d694f11cf071142152aecd528R864) if I'm not mistaken it should be `2ff60e25-30d9-4da6-aa65-e659b46c10d8`

**Comment by antonelepfl** [comment]
Do you have to give a presentation or something with this Use Case?

**Comment by clupascu** [comment]
You are right. The file is 2ff60e25-30d9-4da6-aa65-e659b46c10d8. Sorry for this. I modified my commit. The usecase should be online asap in order to test it before the summit. Thanks.

**Comment by antonelepfl** [comment]
Ok better now.
In order to work properly, you need to change the hard-coded model
```
model_url = 'CA1_pyr_cACpyr_mpg141017_a1-2_idC_20170918151638'
```
by
```
model_url = 'REPLACE_MODEL_HERE'
```

**Comment by clupascu** [comment]
Yes. I know. I will do it asap.

**Comment by antonelepfl** [comment]
I'm not very sure how this Use Case works but I just selected this model `CA1_int_cAC_010710HP2_20180118155959` and I tried with the default configuration to use the button **Place synapses** and I get this error

Screenshot 2020-01-21 at 14 04 58

Do I have to change some parameters to make it work?

**Comment by clupascu** [comment]
This is why I would like to have the usecase in prod. In order to test it with all the models. You got the error because it was not generalized for the list of models. I fixed this, but my kernel dies with the model that you choose. I stiil have to figure why...

**Comment by antonelepfl** [comment]
'Testing' in production sounds like not a good idea...
You can always test the things locally like if you were in production.

You just need to run the application from your computer. If you want I can explain to you how to do it but I thought you guys were testing locally before making even the Pull Request.

Just let me know if you need some help to test it from your side.

**Comment by clupascu** [comment]
I wanted to test in production only the choice of the model + the rest. Of course I was testing every day the rest locally. Anyway now I fixed also the kernel dying problem. Can you please test again and let me know if you can accept the pull request and make the usecase available in prod? Thanks.

**Comment by alex4200** [comment]
Can I find this use case in the DEV environment somewhere in order to test it?

**Comment by antonelepfl** [comment]
Ok I have added a placeholder image and the notebook on github so @alex4200 in case dev works you can test it on staging too.

**Pull request merged**
