### PR TITLE
Add Mouse and Simplification use case

### PR DESCRIPTION
**Pull request by antonelepfl**
Here we will add 2 use cases that are used with the Simulation-Launcher-UI.
To merge this I would need:
## Mouse 2018 Use Case (sim-ui)

- [x] 1) Confirm that it should be under Brain Area Circuit In Silico Experiment category
- [x] 2) I would need a Picture (thumbnail) for Neocortex region
Screenshot 2020-04-21 at 16 17 51
- [x] 3) Is that region name correct?

When you click on SSCx region, a model selection page will appear before opening the Simulation-Launcher-UI
- [x] 4) Is this thumbnail that was taken from [HBP Page](https://www.humanbrainproject.eu/en/brain-simulation/mouse-sscx/) ok?
Screenshot 2020-04-22 at 09 13 42

- [x] 5) Are the details good enough?
- Title:
"Configure and run a mouse Somatosensory Cortex microcircuit using preconfigured HBP model and data"
- Subtitle:
"A circuit of detailed neuron models based on the Ascoli atlas."
- Contributors: 
-Sood Vishal  - vishal.sood@epfl.ch
-Michael Gevaert - michael.gevaert@epfl.ch
-Stefano Antonel  - stefano.antonel@epfl.ch (was a copy and pasted not sure I should be here)

## Simplification Use Case (running simulations with simplified circuit on sim-ui)
- [ ] 6) This use case will be also under Brain Area Circuit In Silico Experiment category -> Hippocampus right?

- [ ] 7) I would need a representative picture for Simplification
Screenshot 2020-04-21 at 16 18 04

- [ ] 8) Details:
- Title: 
"Configure and run a rat hippocampus simplified microcircuit using HBP model and data"
- Subtitle:
""
- Contributors: 
-Aleksei Sanin - aleksei.sanin@epfl.ch
-Michael Gevaert - michael.gevaert@epfl.ch
-Stefano Antonel  - stefano.antonel@epfl.ch (was a copy and pasted not sure I should be here)

- [ ] 9) Where should we put the instructions for generating the query params to pass to the UI? (what he have in our [confluence](https://bbpteam.epfl.ch/project/spaces/display/BBPNSE/Simulation+Launcher+GUI))

### CODE REVIEW

**Comment by antonelepfl** [comment]
Hi @jdcourcol Could you please check / provide the information required for the points on the description when you have some free time? 

Something like:
1) yes it is in Brain Area ..
2) ...

**Comment by jdcourcol** [comment]
1 Brain Area Circuit In Silico Experiment category: yes.
3 Region is Neocortex
4 Thumbnail is correct
5 

Title:
"Configure and run a mouse Somatosensory Cortex microcircuit using preconfigured HBP model and data"

Subtitle:
"A draft reconstruction of the mouse somatosensory microcircuit."

Contributors:
-Vishal Sood, Blue Brain Project, École Polytechnique Fédérale de Lausanne, Switzerland

Hugo Dictus, Blue Brain Project, École Polytechnique Fédérale de Lausanne, Switzerland

Javier DeFelipe, Instituto Cajal (CSIC) and Universidad Politécnica de Madrid, Spain

Alain Destexhe, UNIC-CNRS, Gif-sur-Yvette, France

Jean-Denis Courcol, Blue Brain Project, École Polytechnique Fédérale de Lausanne, Switzerland

Werner Van Geit, Blue Brain Project, École Polytechnique Fédérale de Lausanne, Switzerland

Daniel Keller, Blue Brain Project, École Polytechnique Fédérale de Lausanne, Switzerland

and of course, yourself and Mike !

**Comment by jdcourcol** [comment]
6) This use case will be also under Brain Area Circuit In Silico Experiment category -> Hippocampus right?
I think we should put it under 'Circuit Building'.
> 'network reduction' > hippocampus
7) I would need a representative picture for Simplification
image
8) Details:

Title:
"Reduce a hippocampus network model using Amsalem et al 2020"

Subtitle:
""
Contributors:
-Aleksei Sanin - aleksei.sanin@epfl.ch
-Michael Gevaert - michael.gevaert@epfl.ch
-Stefano Antonel - stefano.antonel@epfl.ch (was a copy and pasted not sure I should be here)
- Oren ? > we should ask. Aleksei can ask.

9) Where should we put the instructions for generating the query params to pass to the UI?
Confluence is enough

**Comment by antonelepfl** [comment]
https://github.com/antonelepfl/usecases/pull/351 and https://github.com/antonelepfl/usecases/pull/343 were created instead of this one. Closing it

**Pull request closed without merging**
