### PR TITLE
Update usecases.json

### PR DESCRIPTION
**Pull request by clupascu**
bluepyopt_analysis link changed: new container analysis and display outputHTML

### CODE REVIEW

**Comment by antonelepfl** [comment]
So now you should wait a couple of minutes until the website is builded and see your changes.
To make sure that you are seeing the latest version of dev environment I have added on the top right corner an indicator of the commit that triggered the build.
In this case should be `5abac39...` if you don't see that probably clean your cache :)

Let me know if you have any question!

**Comment by clupascu** [comment]
You added the indicator of the commit on top right corner of the collab?

**Comment by antonelepfl** [comment]
I have added in my application but if you go to [Collab DEV](https://collab.humanbrainproject.eu/#/collab/8444/nav/65633) you will see something similar
screen shot 2018-02-28 at 15 07 43

**Comment by clupascu** [comment]
ok. now is clear. Thanks.

**Pull request merged**
