### PR TITLE
Merge Dev into Master

### PR DESCRIPTION
**Pull request by antonelepfl**

### CODE REVIEW

**Comment by antonelepfl** [comment]
Alex [tested](https://github.com/antonelepfl/usecases/pull/321#issuecomment-598111987) this use cases and can be merge to PROD

**Comment by antonelepfl** [comment]
As Jenkins plans are failing to build js apps, this merge will have to wait until they fix this.

**Comment by alex4200** [comment]
There is an issue with jenkins?

**Comment by alex4200** [comment]
https://bbpteam.epfl.ch/project/issues/browse/HELP-12088

**Comment by alex4200** [comment]
Add commits have been manually verified, and can be merged to PROD

**Comment by antonelepfl** [comment]
@alex4200 Can you do a quick check if the KappaNeuroon is disabled on DEV?

**Comment by alex4200** [comment]
Yes it looks like KappaNeuron is disabled on DEV

**Comment by antonelepfl** [comment]
These changes are in PROD now.

**Comment by alex4200** [comment]
Commits seem to work in PROD

**Pull request merged**
