### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by clupascu**
Small images for plasticity usecase added

### CODE REVIEW

**Comment by antonelepfl** [comment]
Why 2 Images? you can only put one on the use case

**Comment by clupascu** [comment]
In 'Single Cell Building', there are two images for the 'Optimize a striatal fast-spiking interneuron' usecase. At least it seems... I wanted something similar.

**Comment by clupascu** [comment]
I added just one image for the plasticity usecase. Can you please take a look?

**Comment by antonelepfl** [comment]
With the image that you provided, in the use cases it will look like:
Screenshot 2020-01-31 at 11 49 36

I guess if you rotate the neuron and put the traces close so it is less wide it think it could looks even better. But is up to you

**Comment by clupascu** [comment]
I think it could be ok like it is for now. Thank you for your suggestions.

**Pull request merged**
