### PR TITLE
Added UC Cerebro-cerebellar loops #532 in hbp-bsp-issues

### PR DESCRIPTION
**Pull request by alberto-antonietti**
I have modified the `usecase.json` according to the guidelines and using previous uc as templates.

### CODE REVIEW

**Comment by antonelepfl** [comment]
Hi Alberto,
Thank you for this Pull Request. I fixed just some small issues.

Just to let you know the use case will look like:

Screenshot 2020-03-24 at 09 02 56
Screenshot 2020-03-24 at 09 03 05
And the nav items on the destination Collab:
Screenshot 2020-03-24 at 09 34 39

I tested the notebooks and I have some issues but I would like @alex4200 to test the notebooks and know his feedback.

So I'm having issues with the packages:
- import world
- population_view
- world_populations

**Comment by alberto-antonietti** [comment]
Hi Stefano,
Thank you for the fixes!
The order of the nav items is not the desired one, since the user should proceed in this order: Preparation of the environment -> Calibration -> Simulation

And is probably the reason why you have encountered the import errors, because world, population_view, and world_populations are Python libraries that are installed during the preparation of the environment.

**Comment by alex4200** [comment]
@alberto-antonietti: I had a look at the use cases I copied from your Collab 79916 and I have the following points:

1. The notebook "Preparation of the environment" seems to contain two cells (first and fourth cell) which are superfluous, as it will be added later when the use case is moved to production (no action required from your side). The cells are the "Using this notebook" cell and the second code cell. Please remove them.
2. The notebooks "Calibration" and "Simulation" seem to contain some output data. Please make sure to always "Clear All Output" before saving a notebook
3. The notebook "Calibration" also fails when running the first cell. The module "world" could not be found; am I missing something?

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-bc8989dc0e4b> in <module>()
     19 
     20 import numpy as np
---> 21 import world
     22 from population_view import PopView
     23 from world_populations import Planner, Cortex, SensoryIO, MotorIO, DirectDCN, InverseDCN

ModuleNotFoundError: No module named 'world'
```

I appreciate if you can take a look at the use cases again and let me know when these issues are fixed.

**Comment by alberto-antonietti** [comment]
Hi Alex,
Thank you for the checks.

> @alberto-antonietti: I had a look at the use cases I copied from your Collab 79916 and I have the following points:
> 
> 1. The notebook "Preparation of the environment" seems to contain two cells (first and fourth cell) which are superfluous, as it will be added later when the use case is moved to production (no action required from your side). The cells are the "Using this notebook" cell and the second code cell. Please remove them.

Removed.
> 2. The notebooks "Calibration" and "Simulation" seem to contain some output data. Please make sure to always "Clear All Output" before saving a notebook

Cleared and saved.

> 3. The notebook "Calibration" also fails when running the first cell. The module "world" could not be found; am I missing something?
> 
> ```
> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-1-bc8989dc0e4b> in <module>()
>      19 
>      20 import numpy as np
> ---> 21 import world
>      22 from population_view import PopView
>      23 from world_populations import Planner, Cortex, SensoryIO, MotorIO, DirectDCN, InverseDCN
> 
> ModuleNotFoundError: No module named 'world'
> ```
> 
> I appreciate if you can take a look at the use cases again and let me know when these issues are fixed.

The modules `world`, `population_view`, and `world_populations` should be available in `"/home/jovyan/extra-cereb-nest/Tests"`  after running the preparation of the environment notebook (this path is added to the `PYTHONPATH` in both the Calibration and the Simulation notebooks).

**Comment by antonelepfl** [comment]
For the point 3) I'm a bit confused why this is not being saved. I guess when we restart the Kernel (in the preparation notebook is described) the paths may be reset.

**Comment by alberto-antonietti** [comment]
> For the point 3) I'm a bit confused why this is not being saved. I guess when we restart the Kernel (in the preparation notebook is described) the paths may be reset.

Yes, that is correct. At the beginning of the Calibration and Simulation notebooks I have:

`os.environ["PYTHONPATH"] = "/home/jovyan/extra-cereb-nest/Tests:/opt/amber18/lib/python3.6/site-packages/:/home/jovyan/.local/nrn/lib/python:"`

That can become

`os.environ["PYTHONPATH"] = "/home/jovyan/extra-cereb-nest/Tests:" + os.environ["PYTHONPATH"]`

if you prefer.

**Comment by alex4200** [comment]
@alberto-antonietti Thanks for solving the first two points; for the third point I noticed that  path is missing in `sys.path`. Adding the following line to the cell (after the `import sys` part) solved the import problem for me:

```
import sys
sys.path[0] = '/home/jovyan/nest-simulator-2.18.0-build/lib/python3.6/site-packages/'
sys.path.append("/home/jovyan/extra-cereb-nest/Tests") # line to add
```

I am still testing the rest of the notebook.

**Comment by antonelepfl** [comment]
> The order of the nav items is not the desired one, since the user should proceed in this order: Preparation of the environment -> Calibration -> Simulation

Unfortunately, this is an issue that the platform have and they are not going to fix it for SGA2 so I would suggest you add something like `Step 1 - ...` or `... - (Step 1)` on the NavItems so the users know which is the order.

**Comment by alberto-antonietti** [comment]
> > The order of the nav items is not the desired one, since the user should proceed in this order: Preparation of the environment -> Calibration -> Simulation
> 
> Unfortunately, this is an issue that the platform have and they are not going to fix it for SGA2 so I would suggest you add something like `Step 1 - ...` or `... - (Step 1)` on the NavItems so the users know which is the order.

Thank you for the suggestion, I have changed the json accordingly.

**Comment by antonelepfl** [comment]
Thank you. I think the only thing that we need to update it the notebook (confirm if you did it) as Alex mentioned https://github.com/antonelepfl/usecases/pull/330#issuecomment-603268068

**Comment by alberto-antonietti** [comment]
> Thank you. I think the only thing that we need to update it the notebook (confirm if you did it) as Alex mentioned [#330 (comment)](https://github.com/antonelepfl/usecases/pull/330#issuecomment-603268068)

I confirm I have updated the notebooks with @alex4200 suggestion.

**Comment by antonelepfl** [comment]
Ok I'll merge to DEV so Alex can have a last look

**Comment by antonelepfl** [comment]
Hi @alberto-antonietti If you can provide me an image with a representation of the Brain Area involve so when the user enters here:
Screenshot 2020-03-26 at 12 33 25
he/she sees the different areas it would be good.

You can upload it in this comments so we can discuss it. Thanks

**Comment by alberto-antonietti** [comment]
cerebro_cerebellar_loops

Hi @antonelepfl, I would use this image, that represents the cortical and cerebellar areas involved in the loops. What do you think? I have generated it using the Blue Brain Cell Atlas, I do not know if and how it is possible to cite the resource used to get the image.

**Pull request merged**
