### PR TITLE
Update usecases.json

### PR DESCRIPTION
**Pull request by clupascu**
BuildOwn Single HippoCell - Python3 compatible

### CODE REVIEW

**Comment by antonelepfl** [comment]
These files are python2 right?

**Comment by clupascu** [comment]
Python3

**Comment by antonelepfl** [comment]
I'm sorry, I was using Staging...
I tried to run all the cells in the Config notebook and I'm getting..
Screenshot 2020-03-02 at 15 38 07

In line 6th

**Comment by clupascu** [comment]
I don't get that error...

**Comment by antonelepfl** [comment]
Could you paste here the links to the jupyter notebooks so Alex can have a look and check if he can reproduce the error?

**Comment by clupascu** [comment]
The notebooks are https://collab.humanbrainproject.eu/#/collab/9132/nav/537802 which corresponds to file 4c689aae-0655-4dda-aa8f-bd5c5e4bfb48
https://collab.humanbrainproject.eu/#/collab/9132/nav/530562 corresponds to a6ae229e-1f5d-492d-a4fc-e61fcb4948ad and https://collab.humanbrainproject.eu/#/collab/9132/nav/530563 corresponds to 56a85712-7102-4864-86b4-274ced3755e8. The last two notebooks are the same for Build and rebuild usecases.

**Comment by antonelepfl** [comment]
@alex4200 could you try to run the notebooks?

**Comment by alex4200** [comment]
Tests done for the notebooks: 
4c689aae-0655-4dda-aa8f-bd5c5e4bfb48: Seems to work
a6ae229e-1f5d-492d-a4fc-e61fcb4948ad: Seems to work as well, is also part of the PR 324 (...?)
56a85712-7102-4864-86b4-274ced3755e8: NOT OK.

**Comment by antonelepfl** [comment]
I'll merge this change.
Please Alex test these use cases and they should have the latest model list available.

**Comment by alex4200** [comment]
Tests look good, can be merged to PROD

**Pull request merged**
