### PR TITLE
Added use case olivocerebellar scaffold - issue #529

### PR DESCRIPTION
**Pull request by AliceGem**

### CODE REVIEW

**Comment by antonelepfl** [comment]
Hi Alice,
Can you please provide a picture of your use case?
It could be a representation of what you will get as an output of running your use case or any other image that you wan to show so it is better defined? 
Thank you

**Comment by AliceGem** [comment]
Hi Stefano, ok! I'm sending you by email. It needs to be used as the use case icon in the menu page right? Or is it to be added in the notebook itself? (for now there's 1 image of the network model in the notebook)

**Comment by antonelepfl** [comment]
It is to be use in the menu page (the logo on the left of the Use Case)

Thank you

________________________________

**Comment by antonelepfl** [comment]
Hi Alice,
I tested quickly the notebook and I have some small improvements:
1) in the line `import plotly.plotly as py` I received an error because of some deprecated library so I think you can 
```
!pip install chart-studio
# and change:
import plotly.plotly as py
# to:
import chart_studio.plotly as py
```
2) Then as running the simulation takes a while you can add some estimation with the default params, something like
```
# replace this:
Running simulation
# for:
Running simulation (this can take a while ~40 min)
```

3) On the line `metrics(cells[CELL_TO_PLOT][0], TOT_DURATION, CELL_TO_PLOT)` I get and error. I attached the trace so you can explore: [error-metrics.txt](https://github.com/antonelepfl/usecases/files/4392741/error-metrics.txt)

Thank you for your collaboration!

**Comment by antonelepfl** [comment]
I'll merge this so we can test you further changes on DEV

**Pull request merged**
