### PR TITLE
Added multicompartmental cerebellum usecase

### PR DESCRIPTION
**Pull request by Helveg**
My notebook depends on download other files from the storage through the `hbp_service_client`, will that still work and contain the same files?

### CODE REVIEW

**Comment by antonelepfl** [comment]
Hi @Helveg I have updated the files so they are inside the Cerebellum Models.
I would need a couple of fixes before merging:
- If you can provide an image that represents your use case like what Alice [added](https://github.com/antonelepfl/usecases/blob/dev/src/assets/config_files/usecases.json#L1543)
- I would suggest to modify the title of the [nav item](https://github.com/antonelepfl/usecases/pull/333/files#diff-792ef00d694f11cf071142152aecd528R1555) when this is copied to the Collab. So instead of `Simulation notebook` something a bit more specific like `Multicompartmental Simulation` or similar

**Comment by Helveg** [comment]
@antonelepfl both of your suggestions should be OK now

**Comment by antonelepfl** [comment]
Perfect! thank you!
I'll merge this to DEV

**Comment by alex4200** [comment]
@Helveg I had a look at the notebook "Multicompartmental simulation of the cerebellum" and I have some questions/suggestions: 

1. Can you change the three lines in the second cell from "_ = !..." to just "!..." (i.e. remove the underscore and equal sign? They do not serve any purpose). 
2. What does this 'finalize' do? 
3. Whenever I run the second or third code cell the cell is marked as being executed (i.e. you have `In [*]` on the left), but the kernel is indicated as idle. That is very strange. And I have some animated test saying ( O Installing tools ...)
4. Code error when running the third cell: 


```
---------------------------------------------------------------------------
NeuronError                               Traceback (most recent call last)
/opt/conda/lib/python3.6/site-packages/glia/__init__.py in <module>()
     40         else:
---> 41             manager.start(load_dll=not bool(os.getenv("GLIA_NO_AUTOLOAD_DLL")))
     42 except GliaError as e:

/opt/conda/lib/python3.6/site-packages/glia/glia.py in start(self, load_dll)
     34         self.compile(check_cache=True)
---> 35         self.init_neuron(load_dll=load_dll)
     36 

/opt/conda/lib/python3.6/site-packages/glia/glia.py in init_neuron(self, load_dll)
     43         if load_dll:
---> 44             self.load_neuron_dll()
     45 

/opt/conda/lib/python3.6/site-packages/glia/glia.py in load_neuron_dll(self)
    319             if not self._dll_loaded:
--> 320                 raise NeuronError("Library could not be loaded into NEURON.")
    321         else:

NeuronError: Library could not be loaded into NEURON.

During handling of the above exception, another exception occurred:

NameError                                 Traceback (most recent call last)
<ipython-input-1-cb57ad0131ad> in <module>()
      5 get_ipython().system('{sys.executable} -m pip install rtree mpi4py')
      6 get_ipython().system('{sys.executable} -m pip install pynb-sim==0.2.0 dbbs-scaffold==3.2.8rc0 dbbs_models dbbs_mod_collection')
----> 7 import rtree, scaffold, dbbs_models
      8 finalize_packages()

/opt/conda/lib/python3.6/site-packages/dbbs_models/__init__.py in <module>()
      4 if not os.getenv("SETUPTOOLS_INSTALL"):
      5 
----> 6     from .granule_cell_models import GranuleCell
      7     from .stellate_cell_models import StellateCell
      8     # from .basket_cell_models import BasketCell

/opt/conda/lib/python3.6/site-packages/dbbs_models/granule_cell_models.py in <module>()
      1 import numpy as np
      2 from patch import p
----> 3 from arborize import NeuronModel
      4 from math import floor
      5 

/opt/conda/lib/python3.6/site-packages/arborize/__init__.py in <module>()
----> 1 from .core import NeuronModel
      2 from .synapse import Synapse
      3 
      4 __version__ = "1.0.3"
      5 

/opt/conda/lib/python3.6/site-packages/arborize/core.py in <module>()
      7     from patch import p
      8     from patch.objects import Section
----> 9     import glia as g
     10     from .synapse import Synapse
     11     p.load_file('stdlib.hoc')

/opt/conda/lib/python3.6/site-packages/glia/__init__.py in <module>()
     42 except GliaError as e:
     43     print("GLIA ERROR", e)
---> 44     exit(1)
     45 
     46 

NameError: name 'exit' is not defined
```

You might need to reset your container to see the errors. We also can have a skype call then I can show you the issues if you do not see them.

**Pull request merged**
