### PR TITLE
Change Image for synaptic plasticity use case

### PR DESCRIPTION
**Pull request by clupascu**

### CODE REVIEW

**Comment by alex4200** [comment]
Can you merge these changes please?

**Comment by antonelepfl** [comment]
@clupascu , you can try with both images locally and let us know the results of which you prefer.
To preview them, you can replace locally 
```
https://raw.githubusercontent.com/antonelepfl/usecases/dev/src/assets/images/Plasticity.png
```
by
```
https://raw.githubusercontent.com/antonelepfl/usecases/9ceb348bfb92b50a6acb89aaf998d00aa5e19f4d/src/assets/images/Plasticity.png

or

https://raw.githubusercontent.com/antonelepfl/usecases/9ceb348bfb92b50a6acb89aaf998d00aa5e19f4d/src/assets/images/Plasticity2.png
```

And let us know how they look

**Comment by clupascu** [comment]
@stefanoantonel I tried to run locally the app, but I get

>npm run dev

> bbp-usecase-wizard@1.1.0 dev C:\Users\Utente
> vue-cli-service serve

"vue-cli-service" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bbp-usecase-wizard@1.1.0 dev: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bbp-usecase-wizard@1.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Utente\AppData\Roaming\npm-cache\_logs\2020-03-11T15_57_50_287Z-debug.log

Any suggestion?

**Comment by antonelepfl** [comment]
Did you did `npm install`? In the instructions is specified https://github.com/antonelepfl/usecases#to-run-locally

**Comment by clupascu** [comment]
Yes I did it. I repeated anyway and now I get

﻿ INFO  Starting development server...
 98% after emitting

 ERROR  Failed to compile with 1 errors                                                                          9:39:56

This relative module was not found:

* ./src/main.js in multi (webpack)-dev-server/client?http://localhost:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by antonelepfl** [comment]
HI Carmen, I have added some instructions of how to run the app [here](https://github.com/clupascu/usecases/blob/dev/README.md#to-run-locally-using-docker)

**Comment by clupascu** [comment]
@stefanoantonel  I tried both images locally. I prefer this one

https://raw.githubusercontent.com/antonelepfl/usecases/9ceb348bfb92b50a6acb89aaf998d00aa5e19f4d/src/assets/images/Plasticity2.png

**Comment by antonelepfl** [comment]
So now you commit in your `dev` branch the change 
```
"src": "https://raw.githubusercontent.com/antonelepfl/usecases/dev/src/assets/images/Plasticity2.png",
```
from the usecases.json of your use case and it will be added on this pull request when you push `git push origin dev`

**Comment by antonelepfl** [comment]
And also you should remove the other image that you are not going to use

**Comment by clupascu** [comment]
Done

**Comment by antonelepfl** [comment]
Perfect! Thank you

**Pull request merged**
