### PR TITLE
Update models.json

### PR DESCRIPTION
**Pull request by a1eko**
Changed as suggested by `@antonelepfl` in https://github.com/cnr-ibf-pa/hbp-bsp-issues/issues/176

### CODE REVIEW

**Comment by antonelepfl** [comment]
Hi,
I have already added the title and description for the [use case](https://github.com/antonelepfl/usecases/blob/striatal_optimization/src/assets/config_files/usecases.json#L166) this change in `models.json` is respect to the model. I mean, what is the proper name of the model (str-fs-161205_FS1-BE37A-20180212) and the description about what is this model.

Please let me know if you need some clarification in this.
Cheers

**Comment by a1eko** [comment]
`@antonelepfl` We can call it FS_CELL and describe as 'Striatal fast-spiking interneuron'. It is deposited in Storage as str-fs-161205_FS1-BE37A-20180212.tar.bz2. Should I rename the file as well?

**Comment by antonelepfl** [comment]
So I updated in this Pull Request the title and description.
No need for change in the filename.
The other thing that I would like you to do is change the jupyter notebook if you have not changed already.

**Comment by a1eko** [comment]
@antonelepfl I changed `storageBasePath` in the notebook but not the `optcell`: if I change `optcell` value I need to rename and repackage corresponding file in Storage.

**Comment by antonelepfl** [comment]
Wait I did not understand that.. 
I updated a picture of how the notebook should looks like. Remove some cells and leave
`optcell = 'REPLACE_STRIATAL_MODEL_HERE'`
as it is so I can replace the placeholder `REPLACE_STRIATAL_MODEL_HERE` for the name of the model (currently str-fs-161205_FS1-BE37A-20180212).

So to summarize you will have your Notebook in the private collab where you can test things and then the public collab with the placeholder that I mentioned before.
Are we in the same page for this?

**Comment by a1eko** [comment]
@antonelepfl I see. Just did it for optcell as well.

But then users of our public collab could not run that notebook in the collab, only when it is called from BSP, right? Maybe I should move it to another public collab then?

**Comment by antonelepfl** [comment]
Hi @a1eko that is right, the user will not be able to run it. If you prefer copy the notebook to another public collab that you have is a good idea.
And just to let you know, you don't need to copy the models. You can use the `storageBasePath` from the public collab to retrieve the model.
Please keep me updated.

**Comment by a1eko** [comment]
@antonelepfl Thank you, Stefano! I made a copy of the notebook in the public collab "Basal ganglia data PUBLIC" 
https://collab.humanbrainproject.eu/#/collab/8566/nav/64870
and added you to the team. It refers to the Storage on the main collab
`    storageBasePath = '/SP6 - Basal ganglia/'`
Hope it works. It takes about 10 minutes to finish though.

**Pull request merged**
