### PR TITLE
New IDs for granule cells notebooks

### PR DESCRIPTION
**Pull request by SteMasoli**
New IDs for granule cells notebooks

### CODE REVIEW

**Comment by antonelepfl** [comment]
@SteMasoli Could you point me where is the jupyter notebook for Optimize a cerebellar granule cell multicompartmental model? With the ID ** c60a4b49-644e-4c1d-a6c0-db9aeb5d1fe2**

**Comment by SteMasoli** [comment]
This is strange. 
When i uploaded the file, the code was that one but now is: "9dea71b0-e091-47ba-8db9-1eaa12ec9c46" 
https://collab.humanbrainproject.eu/#/collab/1655/nav/15208?state=uuid%3D9dea71b0-e091-47ba-8db9-1eaa12ec9c46

I have not touched the file since monday.

**Comment by antonelepfl** [comment]
I don't understand either... So let's change the ID in the usecases (Pull Request) and see if everything is ok.

**Comment by SteMasoli** [comment]
Done the pull request with the new ID

**Pull request merged**
