### PR TITLE
Merge Dev into Master

### PR DESCRIPTION
**Pull request by antonelepfl**

### CODE REVIEW

**Comment by antonelepfl** [comment]
We need to add the notebooks on [production_notebooks](https://github.com/antonelepfl/usecases/tree/dev/production_notebooks) folder after testing

**Comment by alex4200** [comment]
Image looks good to me.

**Comment by alex4200** [comment]
@AliceGem Hi, I have some questions/suggestions regarding the "Olivo-Cerebellar microcircuit" use case:

1. The second code cell must be removed. This cell is wrong. This cell will be _added_ to the notebook when a user closes this notebook. 
2. You have not cleared the output before saving your notebook. Always remember to do "Cell -> All Output -> Clear" before saving, otherwise your outputs will be in the notebook.
3. Suggestion: Add the `pip install` for chart-studio one of the upper cells (so you have all pip install in one cell, and you have all commands starting with an exclamation mark separated from actual python code.
4. The import `import chart-studio.plotly as py` does not work neither does `import chart_studio.plotly as py`. 

I strongly suggest that you ask for a container reset and then run your notebook again. Or you can give me your UserID (In Profile) then Im can ask for a quicker container reset.

**Comment by AliceGem** [comment]
> @AliceGem Hi, I have some questions/suggestions regarding the "Olivo-Cerebellar microcircuit" use case:
> 
> 1. The second code cell must be removed. This cell is wrong. This cell will be _added_ to the notebook when a user closes this notebook.
> 2. You have not cleared the output before saving your notebook. Always remember to do "Cell -> All Output -> Clear" before saving, otherwise your outputs will be in the notebook.
> 3. Suggestion: Add the `pip install` for chart-studio one of the upper cells (so you have all pip install in one cell, and you have all commands starting with an exclamation mark separated from actual python code.
> 4. The import `import chart-studio.plotly as py` does not work neither does `import chart_studio.plotly as py`.
> 
> I strongly suggest that you ask for a container reset and then run your notebook again. Or you can give me your UserID (In Profile) then Im can ask for a quicker container reset.

Hi @alex4200, I did the changes in the first 3 points. My UserID is 302461: after the container reset I will check for point 4. Thanks!

**Comment by alex4200** [comment]
Your container has been reset. Please do a test and fix all outstanding issues, then let me know so I can retest

**Comment by AliceGem** [comment]
Hi @alex4200 and @antonelepfl, your suggestions have been implemented!

**Comment by alex4200** [comment]
STAGE version of the use case seems to work now fine. Can be merged to PROD

**Comment by AliceGem** [comment]
Hi @alex4200 and @antonelepfl thanks! Is anything required from my side to have it merged?

**Comment by antonelepfl** [comment]
@alex4200 I have merged the third use cases for the cerebellum (#333) can you have a look please? And if it is good we need to add this to the production notebooks

**Comment by alex4200** [comment]
@antonelepfl I rerun the STAGE version of the "Multicompartmental simulation of the cerebellum" which seems to work now. 

You can now merge this PR

**Pull request merged**
