### PR TITLE
Merge Dev into Master

### PR DESCRIPTION
**Pull request by antonelepfl**

### CODE REVIEW

**Comment by antonelepfl** [comment]
@alex4200 Could you check if you are happy with the molecular use case (ardock) before merging this to master?

**Comment by alex4200** [comment]
Not happy yet, see email and/or ticket

**Comment by antonelepfl** [comment]
@alex4200 I have also removed the scroll bar that you see on the search / create Collab page.

**Comment by antonelepfl** [comment]
I'll merge this but just consider that the ardock UC will be also merged. We can create issues for that if they are not created yet.

**Pull request merged**
