### PR TITLE
Add terms and conditions page

### PR DESCRIPTION
**Pull request by antonelepfl**

### CODE REVIEW

**Comment by antonelepfl** [comment]
We want this to be by Type of use case the acceptance in Trace Analysis should apply for all the Use cases of this type but not for, for example Morphology

**Comment by antonelepfl** [comment]
@jdcourcol I don't know what is the priority of this change to be merged. If you are ok with a global one so far you can merge it. Otherwise I can continue working later

**Comment by antonelepfl** [comment]
@lbologna Before merging I would like to know if you thing this file is good for the term and conditions https://github.com/antonelepfl/usecases/blob/96db320b01a719d9c61157934fb2e9b33ce854a9/src/assets/config_files/terms_and_conditions.md

**Comment by lbologna** [comment]
Will this message be for all the Trace Analysis use cases or only for the
"Feature extraction GUI"?

**Comment by antonelepfl** [comment]
The acceptance is by "category" so this page will be display only once for Trace Analysis, one for Morphology, etc.
You have to set in which Usecases you are using restricted content as for example https://github.com/antonelepfl/usecases/pull/40/commits/272c2afb0888761f43c850f71beb343e29df62b6#diff-792ef00d694f11cf071142152aecd528R30

**Comment by lbologna** [comment]
Yes, that's fine.
Thanks.

**Pull request merged**
