### PR TITLE
Added UUID to multipipsa Usecases and enabled them

### PR DESCRIPTION
**Pull request by StefanGIT**
I have added the UUID in the files section of the corresponding usecases and set them to disabled:false

### CODE REVIEW

**Comment by antonelepfl** [comment]
Hi @StefanGIT I just moved the use cases a bit upper so most of your use cases are in the same block
Screenshot 2020-02-14 at 11 50 39

**Comment by StefanGIT** [comment]
Great, thanks.

**Comment by antonelepfl** [comment]
I would suggest if you can somehow reduce the length of the [entryfile](https://github.com/antonelepfl/usecases/pull/314/files#diff-792ef00d694f11cf071142152aecd528R65)
because when the notebooks are cloned the end user sees something like 

Screenshot 2020-02-14 at 11 39 36

I think it is a bit too long.

**Comment by StefanGIT** [comment]
Ok, i have shortened the entrynames of two usecases. Is this sufficient?

**Pull request merged**
